import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { GRID_DATA_ITEMS } from './data'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {
            GRID_DATA_ITEMS.map((gridDataItem) => {
              const { id, attributes } = gridDataItem;

              return (
                <div key={id}>
                  <Link href={attributes.href}>{attributes.text}</Link>
                </div>
              )
            })
          }
        </div>
        <br />
        {children}
      </body>
    </html>
  )
}
